-- DELETE
-- USE DBSUPERMERCADO_3I;


--1) EXCLUIR DA TABELA PRODUTO, TODOS OS PRODUTOS DO FORNECEDOR 6

DELETE  FROM PRODUTO
WHERE FORNECEDOR_ID = 6

SELECT * FROM PRODUTO
WHERE FORNECEDOR_ID = 6



--2) EXCLUIR O FORNECEDOR 1 DA TABELA DE FORNECEDORES, 
--VERIFIQUE SE TEM FORNECEDOR
--NA TABELA PRODUTO DEVIDO AO RELACIONAMENTO


SELECT * FROM FORNECEDOR
WHERE ID = 1

DELETE FROM PRODUTO
WHERE FORNECEDOR_ID = 1

DELETE FROM FORNECEDOR
WHERE ID = 1


--3) EXCLUIR TODOS OS PRODUTOS 'SABONETE' DE TODAS AS TABELAS 
	-- QUE CONTENHA PRODUTO

	SELECT * FROM PRODUTO
	WHERE NOME LIKE '%SHAMPOO%'

	DELETE FROM PRODUTO
	WHERE NOME LIKE '%SHAMPOO%'

--4) EXCLUIR TODOS OS CLIENTES DA TABELA CLIENTE, QUE NÃO TEM EMAIL

	
DELETE FROM PEDIDO
WHERE CLIENTE_ID IN 
(SELECT ID FROM CLIENTE WHERE EMAIL = '')

DELETE
FROM CLIENTE
WHERE EMAIL = ''



